openapi: 3.0.0
info:
  version: 1.0.1
  title: ''
  description: 'This OpenAPI is the new version and testing to check Github integrationt and i dont want vhnges to be pushed from here to github'
paths: {}